### ISSUE TITLE
Personal Task tracking

### ISSUE THREAD

**Issue by Docteh** [Docteh/vigilant-guacamole#1]
- [ ] Chrome 76 supports `dark mode media query` which means that [NWJS](https://nwjs.io/blog/v0.40.0-beta1/) will too, would like to upgrade betaflight-configurator to that. 
- [ ] update away from macOS 10.10.1
- [ ] Is there still a wacky maccy problem with node v12? can test with NW.js 0.38.1 and above
- [ ] Figure out OS triggered dark mode in linux
